server:
  port: 8763
  context-path: /message
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: message
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
#  mail:
#    host: smtp.163.com
#    username: 1406343123@163.com
#    password: itmayiedu644
#    enable:  true
#    smtp:
#      auth: true
#    starttls:
#      enable: true
#      required: true



